name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Check diff after formatting code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "stable"
      - name: Run make format
        run: |
          make format
          git diff --exit-code --name-only

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "stable"
      - name: Run make lint
        run: |
          make lint

  build:
    name: Build Go code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["stable", "oldstable"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run go build
        run: go build ./...

  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "stable"
      - name: Run go test
        run: go test -race ./...

  mod:
    name: Check diff after tidying go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: "stable"
      - run: |
          go mod tidy
          git diff --exit-code --name-only
